name: example
description: Test environment for Generative UI.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  genui_annotations: any
  genui: any
  json_schema_builder: any
  dio: ^5.9.2
  shared_preferences: ^2.5.5
  crypto: ^3.0.7
  url_launcher: ^6.3.2
  flex_color_picker: ^3.8.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  genui_builder: any

flutter:
  uses-material-design: true
