import 'dart:convert';
import 'package:flutter/material.dart';

/// The core runtime engine for Generative UI.
/// Maps JSON payloads to Flutter widgets using a pre-compiled registry.
class GenUIEngine {
  /// The global registry mapping component identifiers to a Record
  /// containing their factory function and their JSON schema.
  final Map<
    String,
    ({
      dynamic Function(Map<String, dynamic>) fromJson,
      Map<String, dynamic> schema,
    })
  >
  registry;

  const GenUIEngine({required this.registry});

  /// Generates the System Prompt to be injected into the local LLM.
  /// It automatically includes the JSON schemas of all registered components.
  String buildSystemPrompt() {
    // Extract only the schema parts from the registry
    final schemas = registry.values.map((record) => record.schema).toList();

    // Pretty-print the schemas so the LLM understands them perfectly
    final schemasJson = const JsonEncoder.withIndent('  ').convert(schemas);

    return '''
You are a Generative UI assistant embedded in a Flutter application.
Your goal is to build user interfaces by returning an array of JSON objects.
You MUST ONLY use the components defined in the schemas below.
Do not invent properties or components that do not exist.

AVAILABLE COMPONENTS:
$schemasJson

Respond ONLY with a valid JSON array containing the components to render. 
Do not include markdown blocks like ```json or any conversational text.
''';
  }

  /// Parses a JSON map generated by the LLM and returns the corresponding Flutter Widget.
  Widget parse(Map<String, dynamic> json) {
    try {
      // 1. Extract the component type identifier (supports both 'type' and 'component' keys)
      final type = (json['type'] ?? json['component']) as String?;

      if (type == null) {
        return _buildFallbackError(
          'Missing "type" or "component" key in JSON payload.',
        );
      }

      // 2. Look up the Record in the registry
      final record = registry[type];

      if (record == null) {
        return _buildFallbackError(
          'Component "$type" is not registered in GenUI.',
        );
      }

      // 3. Extract properties.
      // Supports flat structures {"type": "A", "prop": "B"},
      // nested structures {"type": "A", "properties": {"prop": "B"}},
      // and A2UI format {"component": "A", "props": {"prop": "B"}}
      final properties =
          json['properties'] as Map<String, dynamic>? ??
          json['props'] as Map<String, dynamic>? ??
          json;

      // 4. Instantiate the widget safely using the fromJson function in the Record
      final widget = record.fromJson(properties) as Widget;

      return widget;
    } catch (e) {
      return _buildFallbackError('Failed to parse widget:\n$e');
    }
  }

  /// Parses a list of JSON maps and returns a list of Widgets.
  List<Widget> parseList(List<dynamic> jsonList) {
    return jsonList.map((item) {
      if (item is Map<String, dynamic>) {
        return parse(item);
      }
      return _buildFallbackError(
        'Expected a JSON object but got ${item.runtimeType}',
      );
    }).toList();
  }

  /// A graceful fallback widget to display when the LLM hallucinates or mapping fails.
  Widget _buildFallbackError(String message) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 4.0),
      padding: const EdgeInsets.all(12.0),
      decoration: BoxDecoration(
        color: Colors.red.shade50,
        border: Border.all(color: Colors.red.shade300),
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.warning_amber_rounded, color: Colors.red),
          const SizedBox(width: 8.0),
          Expanded(
            child: Text(
              'GenUI Render Error:\n$message',
              style: const TextStyle(
                color: Colors.red,
                fontFamily: 'monospace',
                fontSize: 12.0,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
