import 'dart:convert';
import 'package:flutter/material.dart';

/// The core runtime engine for Generative UI.
/// Maps JSON payloads to Flutter widgets using a pre-compiled registry.
class GenUIEngine {
  /// The global registry mapping component identifiers to a Record
  /// containing their factory function and their JSON schema.
  final Map<
    String,
    ({
      dynamic Function(Map<String, dynamic>) fromJson,
      Map<String, dynamic> schema,
    })
  >
  registry;

  const GenUIEngine({required this.registry});

  /// Generates the System Prompt to be injected into the local LLM.
  /// It automatically includes the JSON schemas of all registered components.
  String buildSystemPrompt() {
    final schemas = registry.values.map((record) => record.schema).toList();
    final schemasJson = const JsonEncoder.withIndent('  ').convert(schemas);

    return '''
You are a Generative UI assistant embedded in a Flutter application.
Your goal is to build user interfaces by returning an array of JSON objects.
You MUST ONLY use the components defined in the schemas below.
Do not invent properties or components that do not exist.

AVAILABLE COMPONENTS:
$schemasJson

Respond ONLY with a valid JSON array containing the components to render. 
Do not include markdown blocks like ```json or any conversational text.
''';
  }

  /// Parses a JSON map generated by the LLM and returns the corresponding Flutter Widget.
  /// If [isStreaming] is true, it suppresses hard error widgets for incomplete data,
  /// opting instead to return an empty space while the LLM finishes typing.
  Widget parse(Map<String, dynamic> json, {bool isStreaming = false}) {
    try {
      final type = (json['type'] ?? json['component']) as String?;

      if (type == null) {
        // We are waiting for the LLM to finish typing the "type" key
        return isStreaming
            ? const SizedBox.shrink()
            : _buildFallbackError(
                'Missing "type" or "component" key in JSON payload.',
              );
      }

      final record = registry[type];

      if (record == null) {
        // The LLM has written a type, but it might not be finished (e.g., "UserCa")
        return isStreaming
            ? const SizedBox.shrink()
            : _buildFallbackError(
                'Component "$type" is not registered in GenUI.',
              );
      }

      final properties =
          json['properties'] as Map<String, dynamic>? ??
          json['props'] as Map<String, dynamic>? ??
          json;

      // We attempt to instantiate. If required properties are missing because
      // the LLM hasn't streamed them yet, this will throw an error.
      final widget = record.fromJson(properties) as Widget;
      return widget;
    } catch (e) {
      // If instantiation fails during streaming (usually due to a missing required variable),
      // we gracefully show nothing (or a tiny loader) until the next tokens arrive.
      return isStreaming
          ? const SizedBox.shrink()
          : _buildFallbackError('Failed to parse widget:\n$e');
    }
  }

  /// Parses a list of JSON maps and returns a list of Widgets.
  List<Widget> parseList(List<dynamic> jsonList, {bool isStreaming = false}) {
    return jsonList.map((item) {
      if (item is Map<String, dynamic>) {
        return parse(item, isStreaming: isStreaming);
      }
      return isStreaming
          ? const SizedBox.shrink()
          : _buildFallbackError(
              'Expected a JSON object but got ${item.runtimeType}',
            );
    }).toList();
  }

  Widget _buildFallbackError(String message) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 4.0),
      padding: const EdgeInsets.all(12.0),
      decoration: BoxDecoration(
        color: Colors.red.shade50,
        border: Border.all(color: Colors.red.shade300),
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.warning_amber_rounded, color: Colors.red),
          const SizedBox(width: 8.0),
          Expanded(
            child: Text(
              'GenUI Render Error:\n$message',
              style: const TextStyle(
                color: Colors.red,
                fontFamily: 'monospace',
                fontSize: 12.0,
              ),
            ),
          ),
        ],
      ),
    );
  }

  /// Parses an incomplete JSON string streamed from an LLM and renders the components as they arrive.
  Widget parseStream(String partialJson) {
    final parsedData = _decodePartialJson(partialJson);

    if (parsedData == null) {
      return const Padding(
        padding: EdgeInsets.all(16.0),
        child: CircularProgressIndicator.adaptive(),
      );
    }

    if (parsedData is List) {
      // Pass the streaming flag so incomplete children hide gracefully
      final widgets = parseList(parsedData, isStreaming: true);
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: widgets,
      );
    } else if (parsedData is Map<String, dynamic>) {
      // Pass the streaming flag
      return parse(parsedData, isStreaming: true);
    }

    return _buildFallbackError(
      'Root JSON stream must be an Object or an Array.',
    );
  }

  dynamic _decodePartialJson(String jsonString) {
    if (jsonString.isEmpty) return null;

    String fixedJson = jsonString;
    bool inString = false;
    bool isEscaped = false;
    List<String> stack = [];

    for (int i = 0; i < fixedJson.length; i++) {
      String char = fixedJson[i];
      if (inString) {
        if (char == '\\') {
          isEscaped = !isEscaped;
        } else if (char == '"' && !isEscaped) {
          inString = false;
        } else {
          isEscaped = false;
        }
      } else {
        if (char == '"') {
          inString = true;
        } else if (char == '{' || char == '[') {
          stack.add(char);
        } else if (char == '}') {
          if (stack.isNotEmpty && stack.last == '{') stack.removeLast();
        } else if (char == ']') {
          if (stack.isNotEmpty && stack.last == '[') stack.removeLast();
        }
      }
    }

    if (inString) {
      fixedJson += '"';
    }

    if (fixedJson.trim().endsWith(',')) {
      fixedJson = fixedJson.substring(0, fixedJson.lastIndexOf(','));
    }

    for (int i = stack.length - 1; i >= 0; i--) {
      fixedJson += stack[i] == '{' ? '}' : ']';
    }

    try {
      return jsonDecode(fixedJson);
    } catch (_) {
      return null;
    }
  }
}
