targets:
  $default:
    builders:
      genui_builder|genui:
        enabled: true

builders:
  genui:
    target: ""
    import: "package:genui_builder/builder.dart"
    builder_factories: ["genuiBuilder"]
    build_extensions: { ".dart": [".genui.g.dart"] }
    auto_apply: dependents
    build_to: source