import 'package:flutter/material.dart';
import 'package:genui/genui.dart';
import 'package:genui_annotations/genui_annotations.dart';
import 'genui_registry.g.dart';
import 'widgets/catalog/user_card_widget.dart';
import 'widgets/catalog/task_item_widget.dart';
import 'widgets/catalog/stats_widget.dart';
import 'widgets/interactive_surface.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'GenUI Composed Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
        useMaterial3: true,
      ),
      home: const ComposedScreen(),
    );
  }
}

class ComposedScreen extends StatefulWidget {
  const ComposedScreen({super.key});

  @override
  State<ComposedScreen> createState() => _ComposedScreenState();
}

class _ComposedScreenState extends State<ComposedScreen> {
  bool _isRendered = false;

  // Local state to simulate dynamic interaction updates
  bool _task1Completed = false;
  bool _task2Completed = true;

  void _handleWidgetEvent(String eventJson) {
    final event = GenUiEvent.parse(eventJson);
    if (event == null) return;

    if (event.name == TaskItemWidgetEvents.onToggle) {
      final taskId = event.context['task_id'];
      if (taskId == 'task_1_id') {
        setState(() {
          _task1Completed = !_task1Completed;
        });
      } else if (taskId == 'task_2_id') {
        setState(() {
          _task2Completed = !_task2Completed;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final completedCount =
        (_task1Completed ? 1 : 0) + (_task2Completed ? 1 : 0);

    // 2. Define our components dynamically based on state
    final components = [
      // Root vertical layout Column
      Component(
        id: 'root',
        type: 'Column',
        properties: {
          'children': [
            'header_text',
            'user_card',
            'divider_1',
            'stats',
            'task_1',
            'task_2',
          ],
        },
      ),
      // Heading Text
      const Component(
        id: 'header_text',
        type: 'Text',
        properties: {'text': '### Task Board & Team', 'variant': 'h3'},
      ),
      // Your autogenerated UserCardWidget
      const Component(
        id: 'user_card',
        type: $UserCardWidgetIdentifier,
        properties: {
          'name': 'Ada Lovelace',
          'role': 'Lead Architect',
          'isActive': true,
        },
      ),
      const Component(id: 'divider_1', type: 'Divider', properties: {}),
      // Your autogenerated StatsWidget
      Component(
        id: 'stats',
        type: $StatsWidgetIdentifier,
        properties: {'totalTasks': 2, 'completedTasks': completedCount},
      ),
      // Your autogenerated TaskItemWidget 1
      Component(
        id: 'task_1',
        type: $TaskItemWidgetIdentifier,
        properties: {
          'title': 'Design Generative UI Architecture',
          'isCompleted': _task1Completed,
          'priority': 'high',
          'task_id': 'task_1_id', // Passed inside context
        },
      ),
      // Your autogenerated TaskItemWidget 2
      Component(
        id: 'task_2',
        type: $TaskItemWidgetIdentifier,
        properties: {
          'title': 'Compile schemas with build_runner',
          'isCompleted': _task2Completed,
          'priority': 'medium',
          'task_id': 'task_2_id',
        },
      ),
    ];

    return Scaffold(
      appBar: AppBar(
        title: const Text('GenUI Composed Dashboard'),
        backgroundColor: Colors.teal.shade100,
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            children: [
              if (!_isRendered)
                const Padding(
                  padding: EdgeInsets.symmetric(vertical: 60.0),
                  child: Text(
                    'Press "Render Composed UI" to construct a fully interactive dashboard combining layout and autogenerated widgets.',
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 16, color: Colors.grey),
                  ),
                )
              else
                InteractiveSurface(
                  components: components,
                  catalog: globalGenUICatalog,
                  onEvent: _handleWidgetEvent,
                ),
              const SizedBox(height: 24),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton.icon(
                    onPressed: _isRendered
                        ? null
                        : () => setState(() => _isRendered = true),
                    icon: const Icon(Icons.dashboard_customize),
                    label: const Text('Render Composed UI'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.teal.shade50,
                    ),
                  ),
                  const SizedBox(width: 16),
                  OutlinedButton.icon(
                    onPressed: _isRendered
                        ? () => setState(() {
                            _isRendered = false;
                            _task1Completed = false;
                            _task2Completed = true;
                          })
                        : null,
                    icon: const Icon(Icons.clear),
                    label: const Text('Clear'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
