import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:genui/genui.dart';
import 'package:example/main.dart';
import 'package:example/genui_registry.g.dart';
import 'package:example/presentation/widgets/catalog/user_card_widget.dart';

void main() {
  testWidgets('App renders UserCardWidget from JSON', (
    WidgetTester tester,
  ) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const MainApp());

    // Verify initial instructions text
    expect(
      find.text(
        'Press "Render Composed UI" to construct a fully interactive dashboard combining layout and autogenerated widgets.',
      ),
      findsOneWidget,
    );

    // Tap 'Render Composed UI' button to begin rendering
    await tester.tap(find.widgetWithText(ElevatedButton, 'Render Composed UI'));
    await tester.pumpAndSettle();

    // Verify that the UserCardWidget is rendered with the mocked JSON data.
    expect(find.byType(UserCardWidget), findsOneWidget);
    expect(find.text('Ada Lovelace'), findsOneWidget);
    expect(find.text('Lead Architect'), findsOneWidget);
    expect(find.text('Active'), findsOneWidget);
  });

  testWidgets('Catalog builds UserCardWidget from CatalogItemContext', (
    WidgetTester tester,
  ) async {
    final catalog = globalGenUICatalog;

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Builder(
            builder: (BuildContext context) {
              final catalogContext = CatalogItemContext(
                id: 'test_node',
                type: $UserCardWidgetIdentifier,
                data: const {
                  'name': 'Alan Turing',
                  'role': 'Computer Scientist',
                  'isActive': false,
                },
                dispatchEvent: (_) {},
                buildChild: (_, [_]) => const SizedBox.shrink(),
                buildContext: context,
                dataContext: DataContext(InMemoryDataModel(), DataPath.root),
                getComponent: (_) => null,
                getCatalogItem: (_) => null,
                surfaceId: 'test_surface',
                reportError: (_, [_]) {},
              );

              return catalog.buildWidget(catalogContext);
            },
          ),
        ),
      ),
    );

    expect(find.byType(UserCardWidget), findsOneWidget);
    expect(find.text('Alan Turing'), findsOneWidget);
    expect(find.text('Computer Scientist'), findsOneWidget);
    expect(find.text('Inactive'), findsOneWidget);
  });
}
